import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from "../Components/footer"
import 'react-tabs/style/react-tabs.css';
import "slick-carousel/slick/slick.css"; 
import "slick-carousel/slick/slick-theme.css";
import "react-fancybox/lib/fancybox.css";
import 'aos/dist/aos.css'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head> 
      <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <meta name="description" content="Michods Café For Specialty Coffee Was Opened In 2018 In Jubail 
  Industrial City, And It Is Considered One Of The Unique Brands 
  In Its Field, As It Always Aims To Advance In The World Of Coffee, 
  From The Kingdom Of Saudi Arabia To The Global Markets."/>
  <meta name="keywords" content=""/>
  <link rel="shortcut icon" href="./img/logoo.png" type="image/x-icon"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <title>methods</title>
  </head>
      <body >
        {children}
      <Footer />
      </body>
    </html>
  )
}
